Upgrade to Ruby 2.3.0 to avoid MRI bug
Avoids MRI bug that causes errors like ActionView::Template::Error: undefined method `url_options' for #<Module>.  Also fixes the associated performance issue.